package org.luchini.bgserver.engine.events;

public enum RoomInfoChangeReason {
	NICKNAME_CHANGED, GAME_SPECIFC_DATA_CHANGED, 
	NEW_PLAYER_ENTERED, PLAYER_QUITED, 
	SEAT_TAKEN, SEAT_LEFT,
	STATUS_CHANGED, PLAYERINFO_CHANGED,
	PLAYER_SEATED, PLAYER_LEFT, PLAYER_RESEATED
}
